### ISSUE TITLE
figure out a way to mock tui::widgets::Widget to test if expected text is rendered

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#11]
Would be awesome to be able to unit test exactly if the expected message is printed inside the terminal when calling our functions.

It would make some unit tests more useful.

**Comment by WindowGenerator** [comment]
Hi!
Can I take this issue?
For this, we can use smthng like this: https://github.com/ratatui-org/ratatui/blob/main/tests/widgets_paragraph.rs#L12

**Comment by radlinskii** [comment]
Sure go ahead 🙂
