### ISSUE TITLE
Support non Ascii characters

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#12]
This is required to be able to work with different languages than english.
Currently characters like `ł, ń, ü, ß` break the program because they take more than  1 byte of space inside a string.
We should add support for typing those characters.
This might require refactoring logic of checking character validity and/or displaying the character.

**Comment by WindowGenerator** [comment]
Hi!
Can I take this issue?

**Comment by radlinskii** [comment]
Sure, go ahead :)
