### ISSUE TITLE
add integration tests

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#13]
I tried to add integration tests, but I've failed miserably. Maybe someone more experienced with working with CLI rust will have more luck than me. :)

**Comment by mdrokz** [comment]
> I tried to add integration tests, but I've failed miserably. Maybe someone more experienced with working with CLI rust will have more luck than me. :)

Hey maybe i can pick up where you left off is there any reference ? thanks

**Comment by radlinskii** [comment]
Sure, have a look at files in tests folder. Those tests worked locally on my machine but were failing at GitHub actions.
There is a test terminal backend struct in tui crate that is supposed to be used there, and might be the answer here.

**Comment by mdrokz** [comment]
> Sure, have a look at files in tests folder. Those tests worked locally on my machine but were failing at GitHub actions. There is a test terminal backend struct in tui crate that is supposed to be used there, and might be the answer here.

Thanks i will see can you assign me this issue ?

**Comment by mdrokz** [comment]
> Sure, have a look at files in tests folder. Those tests worked locally on my machine but were failing at GitHub actions. There is a test terminal backend struct in tui crate that is supposed to be used there, and might be the answer here.

i tried running the tests locally the tests hang when i run them through cli and when i debug through vscode i get this error

![image](https://github.com/radlinskii/donkeytype/assets/33598169/2775f737-49d6-4c92-980c-b221c350195b)

**Comment by radlinskii** [comment]
Yeah, I think so.
I think we should try to use https://docs.rs/tui/latest/tui/backend/struct.TestBackend.html in the tests.

**Comment by radlinskii** [comment]
Nice, maybe end-to-end approach is better for this kind of app? What do you think?
Can you share the resources you've found?

**Comment by mdrokz** [comment]
> Nice, maybe end-to-end approach is better for this kind of app? What do you think? Can you share the resources you've found?

Its better to have a mix of end-to-end tests & integration tests so we can see if both the system & binary work i found this library to automate / test interactive cli app https://github.com/zhiburt/expectrl and i was also reading this https://rust-cli.github.io/book/tutorial/testing.html i think it would be better to write integration tests first and then we can write end-to-end tests.

**Comment by radlinskii** [comment]
Thanks 🙏 Go ahead!

**Comment by mdrokz** [comment]
> Thanks 🙏 Go ahead!

Created a PR for the integration tests
