### ISSUE TITLE
save test results to csv

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#2]
Would be really useful to save results of the test that has run into a file so that results can be displayed and compared later on.

This issue is only about writing to a file.
File location can be, `~/.config/donkeytype/results.csv`, because this folder is already used for config file.
`.csv` seems to be the best extension for this purpose.
If the file doesn't exist it should be created.

Different values that are currently displayed in `src/main.rs` after the test is finished should be added as columns into the csv.
Information about settings should also be included, (currently only `duration`, and `numbers` if numbers where present). Later might be beneficial to have this data for filtering the results.

[serde crate](https://crates.io/crates/serde) should be used for this purpose, it is already a dependency.

**Comment by AmeyaVerma** [comment]
@radlinskii I can fix this please assign me with it

**Comment by radlinskii** [comment]
Great, good luck!

**Comment by AmeyaVerma** [comment]
@radlinskii I need some further understanding of this problem. Where are you facing this error ,can you navigate me to the files .

**Comment by radlinskii** [comment]
There is no error here. This issue is about implementing the feature of writing the results that you get at the end of the main function https://github.com/radlinskii/donkeytype/blob/3e2b48cf547ef745a05bf891779a65705ea81623/src/main.rs#L97-L113 to a file so that they can be displayed later on.

**Comment by nisargparikh69** [comment]
@radlinskii  I have raised PR kindly review
