### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#37]
Currently paths for results file and config file are hardcoded to `~/.local` and `~/.config` and they need to be changed to try to support Windows platform.
https://github.com/dirs-dev/dirs-rs is already in the project so it might be handy to use it.
But the paths that it uses are different than `~/.local` and `~/.config` for MacOS, which I'm not a big fan of. I would rather stick to those directories on MacOS still.

Than, once the paths are updated the program would need to be compiled for windows target and tested there.

- [x] change paths
- [ ] fix #39 
- [ ] create release in https://github.com/radlinskii/donkeytype/blob/33a3b08a92333bc258ae9cb53eea0b74d9598812/.github/workflows/release.yml#L15-L16

**Comment by 0Ky** [comment]
I'd like to work on this task, please assign this issue to me.
