### ISSUE TITLE
Windows Double KeyPress Issue

### ISSUE THREAD

**Issue by 0Ky** [radlinskii/donkeytype#39]
On Windows, a single keypress is mistakenly detected twice: once on KeyDown and again on KeyUp.
This issue stems from `crossterm`, you will need to check the `KeyEventKind`:
```rust
if let Event::Key(key) = event {
    if key.kind == KeyEventKind::Press {
        ...
    }
}
```

**Comment by radlinskii** [comment]
Let's keep this as separate issue, but also added it as part of #37
