### ISSUE TITLE
Documentation Missing Information on `save_results` Location

### ISSUE THREAD

**Issue by lemorage** [radlinskii/donkeytype#42]
The README does not provide any information about where these results are stored if `save_results` flag is true. Only when I took some time to see the `test_results.rs`, can I find that the results are saved to a file located in the `.local/share/donkeytype` inside the user's home directory.

It would be more user-friendly if the README could be updated to include this information.

**Comment by radlinskii** [comment]
Makes sense, I agree 👍

**Comment by lemorage** [comment]
I can work on this issue too 🙂

**Comment by radlinskii** [comment]
Perfect, thanks 👌
