### ISSUE TITLE
Feature Request: Allow Custom Storage Locations for `save_results`

### ISSUE THREAD

**Issue by lemorage** [radlinskii/donkeytype#47]
Currently, the `save_results` flag stores the results to `~/.local/share/donkeytype` by default. It would be better to let the user customize the default location.

**Proposed Solution:**

1. Introduce a new option, say `--results-path`, where users can provide their preferred storage location. If this option isn't set, the program can fall back to the default location.
   
2. Alternatively, we could modify the `save_results` flag to accept an optional argument that specifies the storage location. If the argument isn't provided, it defaults to the current behavior.

**Comment by WindowGenerator** [comment]
Can I take this issue or @lemorage u want to do it?

**Comment by lemorage** [comment]
@WindowGenerator Oh no no, I'm just suggesting it, you go for it.
