### ISSUE TITLE
Count WPM only in words that were typed correctly

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#5]
Currently WPM is calculated based on the correct characters.
What [monkeytype](https://monkeytype.com/) does, and I think is cool is that they only count WPM in **words** that don't have any mistake in them. 
Would be nice to try and use the same approach.
It would be much more important to not make any mistakes/ correct the mistakes, so I believe it would be beneficial from learning perspective.

**Comment by MercMayhem** [comment]
I can work on this

**Comment by radlinskii** [comment]
Perfect, good luck!
