### ISSUE TITLE
add argument for custom config file path

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#53]
Similar to https://github.com/radlinskii/donkeytype/issues/47 add argument `--config-path` to specify custom path for config file to be read.
Document it with comment in main.rs and config.rs and add it to Readme.
Add information that this config file should still be `.json`
Make sure the tests are passing.

**Comment by WindowGenerator** [comment]
Hi!
Can I take it?

**Comment by radlinskii** [comment]
Of course 🙂
