### ISSUE TITLE
handle shortcuts for deleting last word from the input

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#6]
On MacOS it makes a lot of sense to have `<Alt>+<Backspace>` deleting characters from current cursor position till beginning of the word (till white space character).
It might be easier to type a word again if there were any mistakes in it.

**Comment by aashirbadb** [comment]
Hi, can I work on this?

**Comment by radlinskii** [comment]
Sure 👍

**Comment by aashirbadb** [comment]
I was able to get `alt+backspace` working but on windows and linux the shortcut to delete last word is `ctrl+backspace`. It looks like crossterm gives `ctrl+h`(konsole, alacritty) or `ctrl+w`(VSCode terminal) when `ctrl+backspace` is pressed. We can probably detect those keys and delete the last word.

Using [`PushKeyboardEnhancementFlags`](https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html) seems to give the correct event but it only works on terminals which support the [kitty keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol)

We can probably use `PushKeyboardEnhancementFlags` for terminals that support it(using [`crossterm::terminal::supports_keyboard_enhancement`](https://docs.rs/crossterm/latest/crossterm/terminal/fn.supports_keyboard_enhancement.html) and use `ctrl+h` and `ctrl+w` if it is not supported. Does that sound good?

**Comment by radlinskii** [comment]
Perfect 👌
