### ISSUE TITLE
add floating window with help instructions

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#66]
Add floating window with help instructions, describing navigation, which is basically a copy paste of what is displayed in the info area above the expected input during test.

But also provide information about basic configuration like passing arguments about test duration, numbers, special characters, and uppercase letters.

Also add information that detailed configuration options are provided when running `donkeytype help`

It should display itself when test is paused / not started when pressing '?'

This mapping should be documented in both code and readme, and maybe added to the info panel as:
"press '?' for more information" or something similar

use Ratatui.rs crate to display the window, I assume it's there

**Comment by theghostmac** [comment]
Hey @radlinskii, subtle reminder to close this issue after review, approval, and merge.
