### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#68]
update readme with new screenshots / gifs because some of the key mappings / layout has changed recently in #57 #60 #63 and #65

**Comment by Arthy22** [comment]
hey I would like to work on this can you assign me this issue

**Comment by kartik-212004** [comment]
I would like to resolve this issue. Please assign it to me.
Thanks

**Comment by radlinskii** [comment]
but I'm gonna close this issue
