### ISSUE TITLE
support uppercase letters at the beginning of words.

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#7]
This could be a new option in the config.

I think the optimal behaviour would be to only make Uppercase letters at the beginning of some words (use ratio logic similar to how numbers are inserted currently).

Option to make whole words UPPERCASE might be a separate issue. (I wouldn't use it 😅, but feel free to create an issue and work on it if you'd like)

User should be able to set this flag as an argument or inside config file.
Default value should be `false`.

**Comment by MercMayhem** [comment]
I can work on this.
