### ISSUE TITLE
support providing numbers ratio in config

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#8]
I've added option to put numbers inside the expected input of a test.
Currently the ratio for putting numbers is hardcode to `0.05` ([see here](https://github.com/radlinskii/donkeytype/blob/3e2b48cf547ef745a05bf891779a65705ea81623/src/expected_input.rs#L27))

The goal of this issue is to enable changing this ratio with config.
User should be able to pass `numbers-ratio` argument to the program or add it to his config file.
Values should be between floating point numbers between `0.0` to `1.0`.  Would be nice to also parse `0` and `1`.

**Comment by milinddethe15** [comment]
Hey I want to work on this issue.  Assign it to me.

**Comment by radlinskii** [comment]
Sure, good luck! 🙂

**Comment by radlinskii** [comment]
Done in #14 thanks @milinddethe15
