### ISSUE TITLE
support symbols

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/donkeytype#9]
Support symbols inside the expected input. 
Could be set as different levels (basic interpunction, programming), or even support user providing a list of symbols that could be used.

This feature should work similar to adding `numbers` inside the expected input. Please have a look inside the source code to see how it happens that if you pass `numbers=true` you can get numbers as part of your test's expected input.

User should be able to set it as an argument when running the program or put it inside her/his config file.

**Comment by kritikash18** [comment]
Hey, can I work on this? Came back here 👋

**Comment by radlinskii** [comment]
Sure 👍

**Comment by kritikash18** [comment]
Raised PR #40

**Comment by phoffmeister** [comment]
Also just created a PR for this #43 . This was an unfortunate timing. There was no update for a week so I looked into this. Then I saw the PR mentioned above. Still wanted to share what I did so far. Feel free to just discard my PR @radlinskii

**Comment by radlinskii** [comment]
after reviewing both PRs I merged #43 because:
- it was better documented,
-  handled tests,
-  didn't introduce new dependency

Sorry @kritikash18 and thanks for your contribution, of course added `hacktoberfest-accepted` label to your PR too
